config/_default/params.toml
themes/zdoc/assets/sass/layout/_header.scss
themes/zdoc/layouts/partials/navbar/icons/light-dark-toggle.html

Set Dark mode as default

---

content/gcp/general-knowledge/_index.md
content/gcp/general-knowledge/gcp-goat.md

Added the GCP goat under the GCP Section

Add GCP GOAT

---

content/aws/general-knowledge/assume_role_logic.md
content/aws/general-knowledge/introduction_user_data.md

* Added a section on how to access user data via the API
* Fixed a few awkward grammar mistakes

Updated and expanded the user data page

---

README.md

* Added 'cd hackingthe.cloud' before trying to run Hugo. Hopefully this fixed any confusion

Fixed a mistake in the README

---

content/aws/avoiding-detection/steal-keys-undetected.md

This slipped by in the previous commit.

Updated EC2 credential exfiltration description for new bypass

---

content/aws/deprecated/whoami.md
content/aws/enumeration/whoami.md

Deprecated the sdb:ListDomains whoami technique

---

content/terraform/terraform_enterprise_metadata_service.md

Fixed an error with a one liner in the TFE article

---

content/aws/exploitation/orphaned_ cloudfront_or_dns_takeover_via_s3.md

Fixed syntax/format for S3 subdomain takeover article.

---

content/aws/avoiding-detection/guardduty-tor-client.md
content/aws/exploitation/orphaned_ cloudfront_or_dns_takeover_via_s3.md
content/aws/general-knowledge/intro_metadata_service.md
content/aws/post_exploitation/aws_consoler.md
content/aws/post_exploitation/get_iam_creds_from_console_session.md
content/aws/post_exploitation/intercept_ssm_communications.md

This addresses #135. I also fixed some descriptions that had double quotes around them (no need)

Fixed the descriptions of several articles.

---

content/aws/exploitation/route53_modification_privilege_escalation.md

This was contributed by @niebardzo

AWS API Call Hijacking

---

content/azure/soft-deleted-blobs.md

Recovering and accessing files in private Storage Accounts that have been deleted

Soft Deleted Blobs

---

content/index.md

a encyclopedia => an encyclopedia

Fix Typo in index.md

---

content/aws/enumeration/enum_iam_user_role.md

Fix typo in unauth user enum.

---

content/aws/post_exploitation/run_shell_commands_on_ec2.md

I've been wanting to add this article for a long time but keep forgetting. Whenever I have a need for this info I've completely forgotten it and have to go digging in the AWS docs to find out. Now it's just a few clicks away on Hacking the Cloud. tbh, that's kind of the whole point of the site :)

Added an article on ssm methods in post exploitation

---

content/aws/enumeration/account_id_from_s3_bucket.md

I had gotten some feedback that the article wasn't very clear on how to use the tool, or what would be needed to setup. I've added some additional info as well as accounted for the name change

Updated the account id from s3 bucket article

---

content/aws/general-knowledge/using_stolen_iam_credentials.md

Frequently I've run into pentesters/red teamers who aren't familiar with how to use IAM credentials. This article covers how to identify them, how to know if they are valid, and some advice around operational security.

Added an article on a methodology for using stolen IAM credentials

---

content/gcp/gcp-buckets.md
content/gcp/general-knowledge/default-account-names.md
content/gcp/general-knowledge/security-and-constraints.md

I decided to add some sections for GCP. I will add more as I have time. Specifically the sections are:
- How service account keys work, what to look for
- How constraints and security permissions work
- Buckets

Added sections for GCP

---

mkdocs.insiders.yml

Issue with mkdocs.insiders.yaml. Fixed it.

Fixed YAML issue

---

content/aws/enumeration/enum_iam_user_role.md

This was identified in #162 by @amkuipers. This PR fixes it.

Updated the link to the iam__enum_roles Pacu module

---

content/aws/general-knowledge/connection-tracking.md

Fixed connection tracking link

---

content/aws/general-knowledge/create_a_console_session_from_iam_credentials.md
mkdocs.insiders.yml

Added some additional context which may be useful

Updated the console session from iam credentials page

---

content/aws/avoiding-detection/guardduty-pentest.md

Fix bad linkage for pacu useragents file

---

content/aws/exploitation/misconfigured_resource-based_policies.md

I must have forgotten to add this when the article was first written. I have since gone in and added it.

Added the NotResource rbp example

---

content/aws/general-knowledge/aws_organizations_defaults.md

Just a short post I've been meaning to write for a long time. While I wouldn't go so far as to call this a vulnerability, it is definitely something you should be aware of considering how common AWS Organizations is, and how big a payoff it is if you compromise the management account.

Added a short post on the defaults of AWS Organizations

---

content/aws/enumeration/whoami.md

Updated the example to use the new error format. This resolves #210

Updated Whoami - Get Principal Name From Keys

---

content/aws/exploitation/Misconfigured_Resource-Based_Policies/misconfigured_ecr_resource_policy.md

Forgot to tokenize the region tags in the commands. Fixed now.

Added region tags for ECR RBP article

---

overrides/main.html

Spreading the holiday cheer :)

Add happy holidays message

---

.github/workflows/build_v2.yml
.github/workflows/deploy_v2.yml
Dockerfile
mkdocs.insiders.yml
mkdocs.yml

I figure that RSS may be a popular value add for folks who use the site. My biggest fear is that this will broadcast any breaking changes I make to the site, so we'll see how it goes.

Soft launch RSS support

---

.github/workflows/build_v2.yml
.github/workflows/deploy_v2.yml
Dockerfile
mkdocs.insiders.yml
mkdocs.yml

Some images on the site can be hard to see on mobile. [glightbox](https://biati-digital.github.io/glightbox/) can help make it easier to use :)

Added glightbox for image zoom

---

content/blog/2022_wrap-up.md

Thank you @christophetd for noticing this!

Grammar fix in 2022_wrap-up.md

---

LICENSE

In response to the [plagiarism incident](https://hackingthe.cloud/blog/2022_wrap-up/#plagiarism) we experienced a few months ago, I am changing the license from MIT to a modified [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. This has the following effects:
```
You are free to:
Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
The licensor cannot revoke these freedoms as long as you follow the license terms.
Under the following terms:
Attribution — You must give [appropriate credit](https://creativecommons.org/licenses/by-nc-sa/4.0/#), provide a link to the license, and [indicate if changes were made](https://creativecommons.org/licenses/by-nc-sa/4.0/#). You may do so in any reasonable …
```

Changed the project License

---

content/aws/enumeration/root_account_from_console.md

Enumerate AWS root account ID from AWS Console

Enumerate AWS root account ID from AWS Console

---

content/aws/enumeration/root_account_from_console.md

Something in wonky with missing titles. It appears to have something to do with `#` characters.

Fix the missing title issue

---

content/aws/enumeration/account_id_from_s3_bucket.md

Currently both s3-account-search and s3-account-finder work, this update means I don't have to rewrite my blogpost

s3-account-search works now

---

content/aws/enumeration/enum_iam_user_role.md
content/azure/enum_email_addresses.md
content/gcp/enumeration/enum_email_addresses.md

Previous PR (#260) had a little typo I didn't catch. No biggie. The outcome was I just needed to add some "---" for a formatting issue.

Fix extra toc's that were added

---

content/aws/exploitation/orphaned_ cloudfront_or_dns_takeover_via_s3.md

Fixed some minor formatting problems.

Fixed some formatting issues with the orphaned CloudFront grid cards

---

dev.Dockerfile

Updated the dev Dockerfile to make testing easier. One of the downsides of the grid cards is that I need to use the paid version of Material for MKDocs. This should make it easier.

Updated dev Dockerfile

---

content/aws/exploitation/cognito_identity_pool_excessive_privileges.md
content/aws/exploitation/cognito_user_self_signup.md

Updated from prior pull request which were missing header details.

Added two new concepts to AWS exploitation associated with Amazon Cognito.

---

content/aws/post_exploitation/download_tools_and_exfiltrate_data_with_aws_cli.md

Added a tip from a [comment](https://www.linkedin.com/feed/update/urn:li:activity:7085273463359176704?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7085273463359176704%2C7085302479327805441%29) on the recent AWS CLI LoLScript article.

Added tip to the AWS CLI lolscript article

---

content/aws/exploitation/iam_privilege_escalation.md

Add IAM privilege escalation techniques regarding deleting or updating IAM permissions boundaries.

Add IAM privilege escalation techniques regarding deleting or updating IAM permissions boundaries

---

README.md

It looks like the format of the badge got updated. I've fixed it :)

Updated the workflow badge

---

overrides/main.html

Added Mastodon to the top banner.

Updated the banner to add Mastodon

---

content/aws/avoiding-detection/steal-keys-undetected.md

This is to resolve #290. I added some additional documentation on how to use STS.

Added usage info for SneakyEndpoints

---

content/aws/enumeration/enumerate_principal_arn_from_unique_id.md

I noticed a small typo in a recent post - here’s a fix.

Fix typo in a recent blog post

---

content/aws/exploitation/s3_server_access_logs.md
content/aws/general-knowledge/aws_organizations_defaults.md

I wrote 2 large blog posts on how to pivot within AWS Organizations, added support for it to Pacu, and built a Pacu enumeration module. Added to this page to help other pentesters.

Update aws_organizations_defaults.md with new AWS Organizations research

---

content/blog/2023_wrap-up.md

I forgot to include the Mastodon link in my bio. Added.

Added Mastodon link to 2023 wrap up

---

content/aws/avoiding-detection/guardduty-pentest.md

Added the Python syntax and line highlights.

Added some minor flair to guardduty-pentest.md

---

content/blog/2023_wrap-up.md

This addresses #315. I'm hoping that by including the count in this article, I can reference it for next year without having to rely on a third party star counter.

Added the star count to the 2023 wrap up

---

content/aws/exploitation/orphaned_cloudfront_or_dns_takeover_via_s3.md

This resolves #314. I updated the article to include the new error message and additional information.

Updated orphaned_cloudfront_or_dns_takeover_via_s3 to reference the new error

---

overrides/main.html

Removed the period from the end of the author byline

---

CONTRIBUTING.md

I'm getting tired of trying to find these when I need them by grepping, so I just added them to the CONTRIBUTING page.

Added card templates to the CONTRIBUTING page

---

content/aws/general-knowledge/iam-key-identifiers.md

This is one of the oldest articles on Hacking the Cloud and I wanted to provide some additional context for it. This PR adds a information card, as well as some context behind important identifier prefixes to be aware of.

Added some additional context to the IAM Key Identifiers article and added a card

---

content/aws/enumeration/enum_iam_user_role.md

Added the cards to the `enum_iam_user_role` article. I think they look really nice!

Added card to enum_iam_user_role

---

content/aws/general-knowledge/connection-tracking.md

Added a card to the connection tracking article

---

content/aws/exploitation/abusing-container-registry.md

Added cards to abusing-container-registry

Added cards to abusing-container-registry

---

CONTRIBUTING.md

Added the Required IAM Permissions card to templates

Added the Required IAM Permissions card to templates

---

content/aws/exploitation/cognito_identity_pool_excessive_privileges.md

Added card to cognito_identity_pool_excessive_privileges

Added card to cognito_identity_pool_excessive_privileges

---

mkdocs.yml

This is the first step to handle #307. This PR updates 2 dependencies to fix the warnings in CI/CD.

Updated Material for MKDocs dependencies

---

content/aws/exploitation/local-priv-esc-mod-instance-att.md

Added card to local-priv-esc-mod-instance-att

Added card to local-priv-esc-mod-instance-att

---

content/aws/exploitation/iam_privilege_escalation.md

Added cards to iam_privilege_escalation

Added cards to iam_privilege_escalation

---

content/aws/exploitation/cognito_user_self_signup.md

Added card to cognito_user_self_signup

Added card to cognito_user_self_signup

---

content/aws/exploitation/Misconfigured_Resource-Based_Policies/index.md

Added a method/tool how resource-based policies can be analyzed for security issues at scale.
Disclaimer: I am the author of this tool.

Added reference to aws-lint-iam-policies

---

CONTRIBUTING.md
content/aws/exploitation/route53_modification_privilege_escalation.md

Added cards to route53_modification_privilege_escalation

Added cards to route53_modification_privilege_escalation

---

content/aws/exploitation/s3-bucket-replication-exfiltration.md

Added card to s3-bucket-replication-exfiltration

Added card to s3-bucket-replication-exfiltration

---

content/aws/post_exploitation/get_iam_creds_from_console_session.md

Added card to get_iam_creds_from_console_session

Added card to get_iam_creds_from_console_session

---

content/aws/post_exploitation/intercept_ssm_communications.md

Added card to Intercept SSM Communications

Added card to Intercept SSM Communications

---

content/aws/post_exploitation/lambda_persistence.md

Added cards to Lambda Persistence

Added cards to Lambda Persistence

---

CONTRIBUTING.md
content/aws/post_exploitation/iam_persistence.md
content/aws/post_exploitation/user_data_script_persistence.md

- Added cards to `user-data-script-persistence`
- Linked the IAM persistence methods article to `user-data-script-persistence`
- Added a new link template to CONTRIBUTING.

Added cards to user-data-script-persistence and added link to IAM persistence methods article

---

content/aws/post_exploitation/run_shell_commands_on_ec2.md

Added cards to run_shell_commands_on_ec2

Added cards to run_shell_commands_on_ec2

---

content/aws/exploitation/Misconfigured_Resource-Based_Policies/misconfigured_iam_role_trust_policy_wildcard_principal.md

I added an article on misconfigured role trust policies that include wildcard principals.

Added article on role trust policies with wildcard principal element

---

mkdocs.insiders.yml

Color isn't right. Should be now.

Updated background color of social cards

---

content/blog/2022_wrap-up.md

In retrospect, I regret not raising awareness about this at the time, as well as calling this out when they launched a training course. They're still doing it, even ripping my own writing off. Some examples [here](https://twitter.com/Frichette_n/status/1753070869109481725?s=20).

Added an admonition about HackTricks Cloud still plagiarizing people's work

---

content/blog/2022_wrap-up.md

Added [this](https://x.com/Frichette_n/status/1753803942377517492?s=20) Twitter thread to the 2022 blog.

Updated HackTricks warning

---

content/aws/enumeration/enumerate_principal_arn_from_unique_id.md

Changed title of Derive a Principal ARN from an AWS Unique Identifier

---

content/azure/abusing-managed-identities.md
content/azure/anonymous-blob-access.md
content/azure/soft-deleted-blobs.md

Finally finished adding all the cards for the various resources on the site. Still need to take care of #348.

Added cards to Azure pages

---

CONTRIBUTING.md
content/aws/deprecated/stealth_perm_enum.md
content/aws/enumeration/account_id_from_s3_bucket.md
content/aws/enumeration/enum_iam_user_role.md
content/aws/enumeration/enumerate_principal_arn_from_unique_id.md
content/aws/exploitation/iam_privilege_escalation.md
content/aws/general-knowledge/aws_organizations_defaults.md
content/aws/general-knowledge/connection-tracking.md
content/aws/post_exploitation/get_iam_creds_from_console_session.md
content/aws/post_exploitation/intercept_ssm_communications.md

This resolves #366. Adding an alt tag to images improves accessibility.

Added alt tag to all profile images

---

content/aws/enumeration/discover_secrets_in_public_aims.md

This article is a shortened version of this [research on public AMIs](https://securitycafe.ro/2024/05/08/aws-cloudquarry-digging-for-secrets-in-public-amis/) by @saw-your-packet and @MatJosephs

Add article about finding secrets in public AMIs

---

content/gcp/enumeration/enumerate_all_permissions.md

Just some minor formatting tweaks for Scott's wonderful GCP enumeration post.

Made some minor tweaks to the recent gcp enumeration article for formatting

---

content/aws/general-knowledge/block-expensive-actions-with-scps.md

Added an article on blocking expensive API calls with SCPs.

Added block expensive AWS API actions with SCPs article

---

content/aws/exploitation/Misconfigured_Resource-Based_Policies/misconfigured_iam_role_trust_policy_wildcard_principal.md

Hello, 
Just a small precision on the condition that enables anyone in the account to assume the role.

Add precision regarding who can assume the role

---

mkdocs.yml

Added Bluesky link

---

content/aws/general-knowledge/aws_cli_tips_and_tricks.md

Added an AWS CLI Tips and Tricks article.

Added AWS CLI Tips and Tricks article

---

content/aws/general-knowledge/connection-tracking.md

Part of the larger (#416) issue for fixing author images. I'm updating this one individually.

Fix author image in connection tracking article

---

content/blog/.pages

Remove unnecessary redirects for the blog pages

---

content/aws/exploitation/Misconfigured_Resource-Based_Policies/exploting_public_resources_attack_playbook.md

A playbook of quick and programmatic attacks against AWS resources that can be made public.

new: playbook exploit public resources

---

content/aws/post_exploitation/iam_persistence.md
content/aws/post_exploitation/iam_rogue_oidc_identity_provider.md

Hello, Nick!
I added a step-by-step guide on how to perform the Rogue OIDC IdP persistence technique.
Let me know if you have any comments about it.
Thank you!
Eduard

AWS post-exploitation IAM persistence with OIDC IdP

---

content/aws/post_exploitation/iam_rogue_oidc_identity_provider.md

Hello again!
The numbering of the steps wasn't as on my local environment so I made them headings to fix it.
Sorry for the second PR.
Thanks!

fix(rogue-iam): number steps
