- content/aws/enumeration/stealth_perm_enum.md
Updated the fact that DirectConnect doesn't appear to be affected anymore, along with the number of services affected
> Updated Stealth Perm Enum Article

- content/aws/avoiding-detection/guardduty-pentest.md
- content/aws/avoiding-detection/guardduty-tor-client.md
- content/aws/avoiding-detection/steal-keys-undetected.md
- content/aws/enumeration/brute_force_iam_permissions.md
- content/aws/enumeration/enum_iam_user_role.md
- content/aws/enumeration/get-account-id-from-keys.md
- content/aws/enumeration/stealth_perm_enum.md
- content/aws/enumeration/whoami.md
- content/aws/exploitation/aws-domain-takeover.md
- content/aws/exploitation/cloudfrunt.md
- content/aws/exploitation/ec2-metadata-ssrf.md
- content/aws/exploitation/escalate-iam-privs.md
- content/aws/exploitation/lambda-steal-iam-credentials.md
- content/aws/exploitation/local-priv-esc-mod-instance-att.md
- content/aws/exploitation/local-priv-esc-user-data-s3.md
- content/aws/exploitation/orphaned_ cloudfront_or_dns_takeover_via_s3.md
- content/aws/general-knowledge/connection-tracking.md
- content/aws/general-knowledge/iam-key-identifiers.md
- content/aws/general-knowledge/intro_metadata_service.md
- content/aws/general-knowledge/introduction_user_data.md
- content/aws/post_exploitation/aws_consoler.md
- content/aws/post_exploitation/intercept_ssm_communications.md
- content/aws/post_exploitation/role-chain-juggling.md
- content/aws/post_exploitation/user_data_script_persistence.md
Previously we had master as the primary branch, and that has since been changed to main. However the links to edit pages were not changed. Should be good to go now.
> Fixed the 'Edit this page' links

- content/aws/post_exploitation/get_iam_creds_from_console_session.md
Original research by Christophe Tafani-Dereeper: https://blog.christophetd.fr/retrieving-aws-security-credentials-from-the-aws-console/?utm_source=pocket_mylist
> Added Get IAM Credentials from a Console Session

- content/aws/exploitation/iam_privilege_escalation.md
ben11kehoe on Twitter pointed out a detail about trust policies that was omitted before. Added to provide better context/detail.
> Added details to the Pass Role EC2 Priv Esc.

- content/aws/post_exploitation/aws_consoler.md
While the source code made it look like you needed sts:GetFederationToken or sts:AssumeRole permissions, using credentials from a role with 0 policies attached still allowed me to generate a token and view resources.
I also added a note to use a Docker container because it can break your existing AWS CLI install
> Revert: Removed permissions needed for AWS Consoler

- content/aws/avoiding-detection/modify-guardduty-config.md
- content/aws/avoiding-detection/modify-security-services.md
Initial commit of a few different configuration changes that a malicious actor could make to a GuardDuty implementation to lessen it's ability to pick up malicious activity.  Depending on how relevant you feel this is, there's probably more to be written up on similar configuration changes to Config & Cloudtrail.
> Modify GuardDuty Configurations

- content/aws/exploitation/lambda-steal-iam-credentials.md
Created a Lambda function with GuardDuty enabled, used it's creds outside of that Lambda, no GuardDuty alert. I figured this was the case but wanted to test it. This PR includes a not for future reference.
> Added note about stolen Lambda credentials

- content/aws/enumeration/account_id_from_ec2.md
With command line access to an ec2 instance, you will be able to enumerate additional detail about the AWS and the instance.
> Enumerate account info from an EC2 instance

- content/aws/post_exploitation/aws_consoler.md
This is in response to https://github.com/Hacking-the-Cloud/hackingthe.cloud/issues/121. Thinking about this more though, It think we may want to scrap this page entirely. Hacking the Cloud should be about techniques, not individual tools. Perhaps in a future update we will remove the aws-consoler page and instead have a 'convert IAM credentials to a console session' page, and just list the two tools there.
> Add aws-vault note

- content/azure/anonymous-blob-access.md
Finding and accessing files stored in Azure Storage Accounts without authentication
> Azure - Anonymous Blob Access

- .github/workflows/build_v2.yml
- .github/workflows/deploy_v2.yml
- mkdocs.insiders.yml
I'm a litle salty about this one. I had to manually debug the git-committers plugin to figure out I needed to specify a very specific configuration (docs_path). This is related to #156
> Added the docs_path config for git-committers

- content/aws/exploitation/ec2-metadata-ssrf.md
> Fixed a typo in the EC2 Metadata SSRF page description

- overrides/main.html
This has been a consistent problem that I was hoping we could address with the git-authors plugin, however it looks like instead we'll need to put it at the top.
> Added an author notice at the top of the article template

- content/blog/.authors.yml
- content/blog/posts/v2_new_look.md
- mkdocs.insiders.yml
I added support for the new Material for MKDocs [blog plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/). Might be an interesting opportunity for guest contributors!
> Added support for the blog plugin

- .github/workflows/deploy_v2.yml
Not sure when this changed, but there are two additional dependencies which are needed. I've added them to the build for GitHub Actions
```
pip install pillow cairosvg
```
> Fixed an MKDocs dependency issue

- content/blog/.authors.yml
- content/blog/v2_new_look.md
- mkdocs.insiders.yml
Turns out that the blog plugin requires use of the nav config, which we don't use. We instead use awesome pages
> Reverted changes to support blog plugin

- content/aws/avoiding-detection/guardduty-pentest.md
- content/aws/avoiding-detection/guardduty-tor-client.md
- content/aws/avoiding-detection/steal-keys-undetected.md
- content/aws/deprecated/stealth_perm_enum.md
- content/aws/deprecated/whoami.md
- content/aws/enumeration/enum_iam_user_role.md
- content/aws/enumeration/get-account-id-from-keys.md
- content/aws/exploitation/abusing-container-registry.md
- content/aws/exploitation/ec2-metadata-ssrf.md
- content/aws/exploitation/lambda-steal-iam-credentials.md
- content/aws/exploitation/local-priv-esc-mod-instance-att.md
- content/aws/exploitation/local-priv-esc-user-data-s3.md
- content/aws/exploitation/orphaned_ cloudfront_or_dns_takeover_via_s3.md
- content/aws/exploitation/route53_modification_privilege_escalation.md
- content/aws/general-knowledge/connection-tracking.md
- content/aws/general-knowledge/iam-key-identifiers.md
- content/aws/post_exploitation/get_iam_creds_from_console_session.md
- content/aws/post_exploitation/role-chain-juggling.md
- content/gcp/capture_the_flag/gcp-goat.md
- content/gcp/exploitation/gcp-metadata-ssrf.md
- content/gcp/exploitation/gcp_iam_privilege_escalation.md
- content/gcp/general-knowledge/default-account-names.md
- content/gcp/general-knowledge/gcp-buckets.md
- content/gcp/general-knowledge/security-and-constraints.md
- content/gcp/tools/gcloud.md
- content/terraform/terraform_ansi_escape_evasion.md
There are a large number of articles that don't have use of the Table of Contents (via Markdown's # feature). As a result, the content of these pages are centered with nothing where the ToC would normally go. This leads to awkard formatting issues and otherwise makes the pages not look as good as they should. I have gone in an applied hide.toc for pages without a table of content, making things look better.
> Hide the table of contents on pages that don't use it

- mkdocs.yml
With the creation of the new Mastodon account, we might as well link to it! https://infosec.exchange/@hackingthecloud
> Add Mastodon to social links

- CONTRIBUTING.md
We recently experienced a situation where our content was plagiarized on another site. In order to be good stewards of the site, we have added clarifying information to our existing plagiarism policy. In particular:
1. If an author would like a link to their page/website removed they have the right to do so
2. Plagiarism of content submitted to Hacking the Cloud is not tolerated and is subject to removal.
3. There is an exception to the plagiarism policy if the original author of the content submits it. This is intended to make it easier for authors to contribute without having to change large chunks of their work.
> Added clarifying information for authors rights

- .github/workflows/build_v2.yml
- .github/workflows/deploy_v2.yml
Seems there is a minor issue with using [mkdocs-glightbox](https://blueswen.github.io/mkdocs-glightbox/) in GitHub actions related to [this](https://github.com/blueswen/mkdocs-glightbox/issues/12). May require future testing but our initial deploy did not work. I'm adding this flag hopefully as a quick fix.
> Add pep517 flag to install mkdocs-glightbox

- content/aws/enumeration/account_id_from_s3_bucket.md
- content/aws/enumeration/brute_force_iam_permissions.md
- content/aws/general-knowledge/create_a_console_session_from_iam_credentials.md
- dev.Dockerfile
Testing out the concept of "info cards" at the top of articles. Currently we have individual links at the top which work, but are not visually appealing. With cards we can make this look better and include extras such as researcher pictures and tool descriptions. This commit is a proof of concept to see what others think.
> Demoing info cards at the top of an article

- mkdocs.yml
For some reason the page edit button is missing. Looking at the [documentation](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#edit-this-page), it appears as if there was a recent change in `9.0.0`. Setting this flag to fix.
> Fixed the missing page edit button

- content/aws/post_exploitation/create_a_console_session_from_iam_credentials.md
As noted in [this](https://www.crowdstrike.com/blog/analysis-of-intrusion-campaign-targeting-telecom-and-bpo-companies/) article from Crowdstrike, [aws_consoler](https://github.com/NetSPI/aws_consoler) was used in the wild. Because of this, I am adding the `Technique seen in the wild` card to the related article.
> Added technique seen in the wild flag to create console session

- CONTRIBUTING.md
I confused the heck out of myself earlier as to why the cards were not properly displaying. Turns out you need a sponsorship to Material for MKDocs for this (I test without it to see what contributors would see). I have added a note to the Contributing doc to help.
> Updated CONTRIBUTING with information on cards

- content/aws/post_exploitation/create_a_console_session_from_iam_credentials.md
The guidance has been updated to include the PACU tool for console access. It has a built-in function for console/open_console. It will automatically be able to use AKIA and ASIA based keys. Thought it would be useful to include.
> Updated the guidance in this particular page on console access.

- content/aws/exploitation/lambda-steal-iam-credentials.md
Based on a report for [Palo Alto](https://unit42.paloaltonetworks.com/compromised-cloud-compute-credentials/#post-125981-_kdq0vw6banab) I have added a Technique Seen in the Wild card for the Steal IAM Credentials and Event Data from Lambda article.
> Add Technique Seen in the Wild card for Steal IAM Credentials and Event Data from Lambda

- content/aws/exploitation/orphaned_ cloudfront_or_dns_takeover_via_s3.md
After reading [this](https://blog.lightspin.io/discover-dangling-domains-that-point-to-your-cloud-assets-to-prevent-subdomain-takeover) article from Lightspin, I wanted to add it as a reference to the dangling subdomain article. This also served as an excellent opportunity to add grid cards.
> Updated references with grid cards for dangling subdomain article

- content/aws/exploitation/cognito_identity_pool_excessive_privileges.md
- content/aws/exploitation/cognito_user_self_signup.md
There were two random `Summary` headers on some articles that weren't needed. I removed them :)
> Removed two unneeded summary headers in articles

- content/aws/post_exploitation/download_tools_and_exfiltrate_data_with_aws_cli.md
For #272 : This PR adds a very short blog post on using the AWS CLI as a LOLScript to download and exfiltrate data. It's so short (and sort of obvious) but I wanted to include it. Perhaps later down the line I could reformat the article into a general LOLBin/LOLScript page that has multiple?
> Added article: Download Tools and Exfiltrate Data with the AWS CLI

- content/aws/exploitation/ec2-metadata-ssrf.md
I happened to see the [Steal EC2 Metadata Credentials via SSRF](https://hackingthe.cloud/aws/exploitation/ec2-metadata-ssrf/) article mentioned in a [YouTube](https://www.youtube.com/watch?v=r7HV4s-4ksQ) video and got excited! I then re-read the article and was disappointed. 
This was one of the first articles I ever wrote for the site, and it is clearly showing its age. Particularly with the quality of the writing. Because this is one of the most popular pages on the entire site, I an opening this PR to improve it.
> Improved the EC2 SSRF article

- content/aws/post_exploitation/iam_persistence.md
- content/aws/post_exploitation/maintain_persistence_with_sts_getfederationtoken.md
- content/aws/post_exploitation/survive_access_key_deletion_with_sts_getfederationtoken.md
This is to satisfy #243. I wrote an article on how `sts:GetFederationToken` can be used to maintain persistence, even when the original IAM credentials have been deactivated or deleted. I debated adding this to the [existing](https://hackingthe.cloud/aws/post_exploitation/iam_persistence/) IAM persistence method page, but ultimately decided to break it out into its own article due to its length.
> Added an article on using sts:GetFederationToken

- content/aws/deprecated/whoami.md
- content/aws/enumeration/whoami.md
This resolves #294. Recently AWS added data plane logging to SNS which broke the method for getting the identity of the keys. `sqs:ListQueues` was a drop in replacement so I have updated the article to reflect this. I double checked both the [documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-logging-using-cloudtrail.html) and tested myself that `ListQueues` doesn't log to CloudTrail, and there is no optional method to get it to log.
> Updated the whoami article with a new method

- mkdocs.yml
Added permalink support for headings based on [this](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=permalink#table-of-contents) documentation.
> Added permalink support for headings

- content/aws/enumeration/enumerate_principal_arn_from_unique_id.md
- content/aws/general-knowledge/iam-key-identifiers.md
This handles #297. Aidan was kind enough to write a short article on his technique for me to reference in the post.
> Added Aidan's technique to find a principal's ARN from a unique identifier

- content/aws/enumeration/enum_iam_user_role.md
While working today I noticed that the resources section was not in the right order with the introductory paragraph. I have switched them out and it should be good now.
> Fixed the order of the Enumerate IAM User/Role article

- .github/workflows/build_v2.yml
- .github/workflows/deploy_v2.yml
Saw a [warning](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/) in the GitHub UI to update our GitHub Action dependencies.
> Updated GitHub Action dependencies

- CONTRIBUTING.md
I realized that if you were using GitHub only then the card templates would be rendered already, so you wouldn't know what to copy. I put them in a code block to account for this.
> Added a code block to the CONTRIBUTING page

- content/stylesheets/extra.css
- mkdocs.yml
This is for #318. Long story short the default theme of Material for MKDocs (our CMS) changed. The result is that it can be difficult to read sometimes due to how dark the background color is. I've brightened it up quite a bit and reverted to a previous background color. Will need to test this to make sure there are no weird impacts.
> Added custom background color

- content/stylesheets/extra.css
- mkdocs.yml
This reverts commit c947a67533c4738130e0dca29ccc65ff0810f549. I botched the color changes in multiple ways. This also made me realize that if changes are made around the colors (For example, MKDocs adds something new) then my stuff may look hella jank. I'm going to explore the [hue](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes) stuff from the documentation to see if that helps.
> Revert "Added custom background color"

- content/stylesheets/extra.css
- mkdocs.yml
This is a better method for fixing the color issues described in #318. I've overwritten the `--md-default-bg-color` field with an easier to see color.
> Added better background color handling

- content/aws/enumeration/get-account-id-from-keys.md
This resolves #340. I added Aidan and Tal's research to the `get-account-id-from-keys` page.
> Updated get-account-id-from-keys to include Aidan and Tal's research

- content/aws/avoiding-detection/modify-guardduty-config.md
Added cards to modify-guardduty-config
> Added cards to modify-guardduty-config

- content/aws/exploitation/local_ec2_priv_esc_through_user_data.md
I wanted to make it more clear that these techniques are for privilege escalation on an EC2 instance, and not in the AWS account (IAM priv esc). I added an intro to compensate for this.
> Added intro to local_ec2_priv_esc_through_user_data

- content/aws/exploitation/abusing-container-registry.md
This handles #348. All Required IAM Permissions cards now use a standardized icon.
> Standardized required iam permissions icons

- content/aws/enumeration/enumerate_principal_arn_from_unique_id.md
The host name in one of the reference links was pointed to `localhost:8000` instead of `https://hackingthe.cloud`.
> Fixed bad link in enumerate_principal_arn_from_unique_id.md

- content/aws/enumeration/account_id_from_s3_bucket.md
There is an update to the note at the bottom of this page. While it appears that it's just GetBucket you need, when using the S3-Account-Finder tool unless you have [READ] ACL Access it appears that this tool will not enumerate anything. We used this file to discover this:
github.com/sa7mon/s3scanner@latest
If you run the tool with a bucket with GetBucket you will not get any ACLs but instead if you run the tool with the Public ACL you can now get the S3 Finder to use.
> Account ID Operational Security Update

- content/aws/enumeration/enumerate_root_email_from_console.md
Not sure why this enumeration method was removed, it's still valid
> Enumerate root email address from AWS Console

- content/azure/abusing-managed-identities.md
This change updates the language used on the abusing managed identities page to fix grammatical errors or run on sentences to clarify the content without. Making it more readable.
> Fix: Spelling and grammar for abusing managed identities page

- content/gcp/enumeration/enumerate_all_permissions.md
Noticed hackingthe.cloud seemed to only have enumerate service accounts? Added a page to cover enumerating all permission for GCP using a service account as an example. Explain testIamPermissions, show gcpwn with --iam on single service or with enum_all. Finally show how you can brute force ~9500 permissions at the end using the tool. Talk from fwd:cloudsec is here: https://www.youtube.com/watch?v=opvv9h3Qe0s.
> Add Enumeration for ALL services for GCP

- content/aws/exploitation/lambda-steal-iam-credentials.md
Updated the Lambda exploitation article to reflect recent [changes](https://x.com/astuyve/status/1825676633673769334).
> Updated Lambda exploitation article

- content/aws/exploitation/orphaned_cloudfront_or_dns_takeover_via_s3.md
In [DNS and CloudFront Domain Takeover via Deleted S3 Buckets](http://localhost:8000/aws/exploitation/orphaned_cloudfront_or_dns_takeover_via_s3/) doc there is a broken link referencing `Discover Dangling Domains that point to your cloud assets to prevent subdomain takeover` which is no longer available. It seems (assumption, having not read the original) that the article has been archived [here](https://securityboulevard.com/2023/05/discover-dangling-domains-that-point-to-your-cloud-assets-to-prevent-subdomain-takeover/). I don't know if Hacking The Cloud wants to reference that archive, another in its place, or anything. For now just removing the reference.
I think this was probably broken since Cisco acquired lightspin.io.
> Remove Broken Link in Domain Takeover

- content/aws/exploitation/local_ec2_priv_esc_through_user_data.md
Throwing this up, but let me know if I'm missing something - we're outside my wheelhouse :).
My understanding is `#cloud-boothook` is a straightforwardly better approach than the current documented `cloud-config`, and also is what dagrz uses in the linked source
> update: Add cloud-boothook tip for user data
